version: '3'

services:

  typo3-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
      args:
        - password=rootpw
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=typo3
      - MYSQL_PASSWORD=typo3pw
      - MYSQL_DATABASE=typo3

  typo3:
    image: martinhelmich/typo3:8
    ports:
      - "80:80"
    links:
      - typo3-db:db
